teknosatis/teknosatis/Controllers/UrunsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using teknosatis.DAL;
using teknosatis.Models;

namespace teknosatis.Controllers
{
    public class UrunsController : Controller
    {
        private teknosatisContext db = new teknosatisContext();

        // GET: Uruns
        [Filter.Admin]
        public ActionResult Index()
        {
            return View(db.Uruns.ToList());
        }

        // GET: Uruns/Details/5
        [Filter.Admin]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Urun urun = db.Uruns.Find(id);
            if (urun == null)
            {
                return HttpNotFound();
            }
            return View(urun);
        }

        // GET: Uruns/Create
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Urun urun, HttpPostedFileBase resim)
        {
            if (ModelState.IsValid)
            {
                db.Uruns.Add(urun);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(urun);
        }

        // GET: Uruns/Edit/5
        [Filter.Admin]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Urun urun = db.Uruns.Find(id);
            if (urun == null)
            {
                return HttpNotFound();
            }
            return View(urun);
        }

        // POST: Uruns/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Filter.Admin]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Ad,Detay,Kategori,Fiyat,ResimYol,Adet")] Urun urun)
        {
            if (ModelState.IsValid)
            {
                db.Entry(urun).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(urun);
        }

        // GET: Uruns/Delete/5
        [Filter.Admin]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Urun urun = db.Uruns.Find(id);
            if (urun == null)
            {
                return HttpNotFound();
            }
            return View(urun);
        }

        // POST: Uruns/Delete/5
        [Filter.Admin]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Urun urun = db.Uruns.Find(id);
            db.Uruns.Remove(urun);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

teknosatis/teknosatis/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>@ViewBag.Title</title>

    <link rel="shortcut icon" href="~/favicon.ico" />

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
        <div class="container-fluid">
            <div class="navbar-header">

                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

                <div class="navbar-brand">
                    <img src="~/Content/images/logo.png" width="36" height="36" alt="teknosatis-@DateTime.Now.Year" />
                    </div>
                    @Html.ActionLink("teknosatis", "Index", "Home", null, new { @class = "navbar-brand" })
                </div>

            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                @using (Html.BeginForm("Arama", "Home", FormMethod.Post, new { @class = "navbar-form navbar-left" }))
                {
                    <div class="form-group">
                        <input name="arama" id="arama" type="text" class="form-control" placeholder="@teknosatis.Resources.lang.NeAramistiniz">
                    </div>
                    <button type="submit" class="btn btn-default">@teknosatis.Resources.lang.Ara</button>
                }
                <ul class="nav navbar-nav navbar-right">


                    @if (Session["Yetki"] != null)
                    {
                        @Html.Partial("_LoginPartial")
                        List<teknosatis.Models.Urun> sepet = Session["sepet"] as List<teknosatis.Models.Urun>;
                        int sepet_urun_sayisi = 0;
                        if (sepet != null && sepet.Count > 0)
                        {
                            sepet_urun_sayisi = sepet.Count;
                        }
                        string rutbe = Session["Yetki"] as string;
                        if (rutbe == "Yönetici")
                        {
                            <li>@Html.ActionLink(@teknosatis.Resources.lang.AdminPanel, "AdminPanel", "Uyes")</li>
                        }
                        else if (rutbe == "Editör")
                        {
                            <li>@Html.ActionLink(@teknosatis.Resources.lang.UrunPaneli, "Index", "Uruns")</li>
                        }
                        <li>@Html.ActionLink(Session["Username"].ToString(), "Profil", "Uyes")</li>
                        <li><a href="/Sepet">@teknosatis.Resources.lang.Sepet <span class="badge">@sepet_urun_sayisi</span></a></li>
                        <li>@Html.ActionLink(@teknosatis.Resources.lang.CikisYap, "CikisYap", "Uyes")</li>
                    }
                    else
                    {
                        @Html.Partial("_LoginPartial")
                        <li>@Html.ActionLink(@teknosatis.Resources.lang.GirisYap, "GirisYap", "Uyes")</li>
                        <li>@Html.ActionLink(@teknosatis.Resources.lang.UyeOl, "UyeOl", "Uyes")</li>
                    }


                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - teknosatis <a href="@Url.Action("Profil","Uyes")">@Session["username"]</a></p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>