teknosatis/teknosatis/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using teknosatis.Models;
using teknosatis.DAL;
using PagedList;
using System.Globalization;

namespace teknosatis.Controllers
{
    public class HomeController : Controller
    {
        private teknosatisContext db = new teknosatisContext();
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Arama(string arama)
        {
            var items = (from p in db.Uruns where (p.Ad.Contains(arama) || p.Detay.Contains(arama) || p.Kategori.Contains(arama)) orderby p.ID descending select p).ToPagedList(1, 4);
            ViewBag.aranan = arama;
            return View(items);
        }

        [Route("Home/Arama/{arama}/{sayfa}")]
        public ActionResult Arama(string arama, int sayfa)
        {
            var items = (from p in db.Uruns where (p.Ad.Contains(arama) || p.Detay.Contains(arama) || p.Kategori.Contains(arama)) orderby p.ID descending select p).ToPagedList(sayfa, 4);
            ViewBag.aranan = arama;
            return View(items);
        }

        [Route("Urunler/{Kategori}/{sayfa}")]
        public ActionResult Listele(string Kategori, int sayfa = 1)
        {
            ViewBag.Title = Kategori;
            ViewBag.Kategori = Kategori;
            var query = (from p in db.Uruns where (p.Kategori == Kategori) orderby p.ID descending select p).ToPagedList(sayfa, 4);
            return View(query);
        }

        public ActionResult UrunDetay(int id = 0)
        {
            if (id == 0)
            {
                return RedirectToAction("Index");
            }
            Urun urun;
            urun = db.Uruns.Find(id);
            db.SaveChanges();
            return View(urun);
        }
        public ActionResult ChangeCulture(string lang,string returnUrl)
        {
            Session["Culture"] = new CultureInfo(lang);
            return Redirect(returnUrl);
        }
        public ActionResult index_goster()
        {
            teknosatisContext db = new teknosatisContext();
            List<Urun> urun6 = db.Uruns.OrderByDescending(i => i.ID).Take(6).ToList();
            return PartialView(urun6);
        }
    }
}

teknosatis/teknosatis/Controllers/SepetController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using teknosatis.Models;
using teknosatis.DAL;

namespace ayakkabisatis.Controllers
{
    public class SepetController : Controller
    {
        private teknosatisContext db = new teknosatisContext();
        // GET: Sepet
        public ActionResult Index()
        {
            if (Session["uye_id"] == null)
                return RedirectToAction("GirisYap", "Uyes");
            List<Urun> listeDondur = new List<Urun>();
            if (Session["sepet"] == null)
            {
                return View(listeDondur);
            }
            listeDondur = (List<Urun>)Session["sepet"];
            return View(listeDondur);
        }

        public ActionResult SepetEkle(int id)
        {
            List<Urun> liste = new List<Urun>();
            Urun tmp = db.Uruns.Find(id);
            if (tmp == null)
            {
                return RedirectToAction("Index");
            }
            if (tmp.Adet == 0)
            {
                return Content("<script>alert('Bu üründen stokda kalmamıştır.');window.history.back(-1);</script>", "text/html");
            }
            if (Session["uye_id"] == null)
            {
                RedirectToAction("GirisYap", "Uyes");
            }
            if (Session["sepet"] != null)
                liste.AddRange((List<Urun>)Session["sepet"]);
            liste.Add(tmp);
            Session["sepet"] = liste;
            return RedirectToAction("Index");
        }
        public ActionResult Cikar(int id)
        {
            List<Urun> listeCikar = new List<Urun>();
            listeCikar = (List<Urun>)Session["sepet"];
            Urun tmp = listeCikar.Find(x => x.ID == id);
            if (tmp == null)
            {
                return RedirectToAction("Index");
            }
            listeCikar.Remove(tmp);
            Session["sepet"] = listeCikar;
            return RedirectToAction("Index");
        }
        public ActionResult SatinAl()
        {
            if (Session["uye_id"] == null)
            {
                return RedirectToAction("GirisYap", "Uyes");
            }
            if (Session["sepet"] == null)
            {
                return Content("<script>alert('Sepette satın alınacak ürün bulunmamaktadır.');window.location='/Uyes/Profil';</script>", "text/html");
            }
            List<Urun> listeSil = new List<Urun>();
            listeSil = (List<Urun>)Session["sepet"];
            Urun tmp;
            foreach (var i in listeSil)
            {
                tmp = db.Uruns.Find(i.ID);
                if (tmp.Adet >= 1)
                {
                    tmp.Adet--;
                    db.SaveChanges();
                }
                else
                    continue;
            }
            Session["sepet"] = null;
            return Content("<script>alert('Ürünler satın alındı.');window.location='/Sepet/Index';</script>", "text/html");
        }
    }
}

teknosatis/teknosatis/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

teknosatis/teknosatis/Views/Home/Arama.cshtml
@using PagedList
@using PagedList.Mvc
@model IPagedList<teknosatis.Models.Urun>

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title></title>
</head>
<body>
    <hr />
    <div class="row">
        @if (Model.Count() == 0)
        {
            <div class="row text-center"><h1>Aranan sonuç bulunamadı.</h1></div>
        }
        @foreach (var i in Model)
        {
            <div class="col-sm-4 col-xs-6 col-md-3 text-center">
                <div class="thumbnail">
                    <a href="@Url.Action("UrunDetay/"+@Html.DisplayFor(item => i.ID))"><img src=@Html.DisplayFor(item => i.ResimYol) class="img-responsive" alt="..." style="width:350px;height:400px;"></a>
                    <div class="caption">
                        <h3>@Html.DisplayFor(item => i.Ad)</h3>
                        <b>@Html.DisplayFor(item => i.Detay)</b>
                        <p><span class="label label-success">@Html.DisplayFor(item => i.Fiyat) TL</span></p>
                    </div>
                </div>
            </div>
        }
    </div>
    <div class="pagedList row text-center">
        @Html.PagedListPager(Model, sayfa => Url.Action("Arama/" + ViewBag.aranan + "/" + sayfa), PagedListRenderOptions.PageNumbersOnly)
    </div>

</body>
</html>

teknosatis/teknosatis/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

teknosatis/teknosatis/Views/Home/Index.cshtml
@{
    ViewBag.Title = "teknosatis";
}

<hr />
<div class="row">
    <div class="col-md-3 col-xs-12">
        @RenderPage("~/Views/Home/Kategori.cshtml")
        <hr />
    </div>

    <div class="col-md-9 col-xs-12">
        <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
            <!-- Indicators -->
            <ol class="carousel-indicators">
                <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                <li data-target="#carousel-example-generic" data-slide-to="2"></li>
                <li data-target="#carousel-example-generic" data-slide-to="3"></li>
            </ol>

            <!-- Wrapper for slides -->
            <div class="carousel-inner">
                <div class="item active">
                    <img src="http://www.thesource.ca/medias/8028768-A-mediaConversion-original-1-mediaConversion-640-x-480-mediaConversion-400-x-300-0?context=bWFzdGVyfGltYWdlc3w0OTIyM3xpbWFnZS9qcGVnfGltYWdlcy9oNTAvaGFkLzg4MjU3MDg2MDk1NjYuanBnfGY2OGU5NzY0MGQ3OTVjMTAwYjJjODJjYzZiZjZjMzU1NDQ2MGVmMTQxNzg1MGQ5M2I2ZjAxMWEwNzE0M2VkYjU"  alt="...">
                    <div class="carousel-caption">
                        <h3 style="color:blue">Kulaklık</h3>
                    </div>
                </div>
                <div class="item">
                    <img src="http://www.lenovo.com/images/OneWebImages/FormFactor/Laptops/Lenovo/400x300/lenovo-laptop-yoga-500-series.png" alt="...">
                    <div class="carousel-caption">
                        <h3 style="color:blue">Bilgisayar</h3>
                    </div>
                </div>
                <div class="item">
                    <img src="http://www3.lenovo.com/medias/tab-2-a8-splitter.png?context=bWFzdGVyfHJvb3R8OTg1NTl8aW1hZ2UvcG5nfGhhMS9oN2UvOTI0NTQ1MjU5OTMyNi5wbmd8ZDM5YzAyNzFhYWEwODc5MjBjMTEwNTFmMTYzOTM2NDM2ZDczYThmMWU3MDljNGQ4OWQ0OTQyMzI5NzZhYzIzOA" alt="...">
                    <div class="carousel-caption">
                        <h3 style="color:blue">Tablet</h3>
                    </div>
                </div>
                <div class="item">
                    <img src="http://store.storeimages.cdn-apple.com/4662/as-images.apple.com/is/image/AppleInc/aos/published/images/s/eg/segment/hero/segment-hero-iphonese-201609?wid=400&hei=300&fmt=png-alpha&qlt=95&.v=1473014761782" alt="...">
                    <div class="carousel-caption">
                        <h3 style="color:blue">Telefon</h3>
                    </div>
                </div>
            </div>

            <!-- Controls -->
            <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
                <span class="glyphicon glyphicon-chevron-left"></span>
            </a>
            <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
                <span class="glyphicon glyphicon-chevron-right"></span>
            </a>
        </div>
    </div>
    @Html.Action("index_goster")
</div>

teknosatis/teknosatis/Views/Home/Item.cshtml
@{
    ViewBag.Title = "Item";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Shop Item - Start Bootstrap Template</title>
    <!-- Bootstrap Core CSS -->
    <link href="css/bootstrap.min.css" rel="stylesheet">
    <!-- Custom CSS -->
    <link href="css/shop-item.css" rel="stylesheet">
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>
    <!-- Page Content -->
    <div class="container">
        <div class="row">
            <div class="col-md-3">
                <p class="lead">Shop Name</p>
                <div class="list-group">
                    <a href="#" class="list-group-item active">Category 1</a>
                    <a href="#" class="list-group-item">Category 2</a>
                    <a href="#" class="list-group-item">Category 3</a>
                </div>
            </div>
            <div class="col-md-9">
                <div class="thumbnail">
                    <img class="img-responsive" src="http://placehold.it/800x300" alt="">
                    <div class="caption-full">
                        <h4 class="pull-right">$24.99</h4>
                        <h4>
                            <a href="#">Product Name</a>
                        </h4>
                        <p>See more snippets like these online store reviews at <a target="_blank" href="http://bootsnipp.com">Bootsnipp - http://bootsnipp.com</a>.</p>
                        <p>
                            Want to make these reviews work? Check out
                            <strong>
                                <a href="http://maxoffsky.com/code-blog/laravel-shop-tutorial-1-building-a-review-system/">this building a review system tutorial</a>
                            </strong>over at maxoffsky.com!
                        </p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum</p>
                    </div>
                    <div class="ratings">
                        <p class="pull-right">3 reviews</p>
                        <p>
                            <span class="glyphicon glyphicon-star"></span>
                            <span class="glyphicon glyphicon-star"></span>
                            <span class="glyphicon glyphicon-star"></span>
                            <span class="glyphicon glyphicon-star"></span>
                            <span class="glyphicon glyphicon-star-empty"></span>
                            4.0 stars
                        </p>
                    </div>
                </div>
                <div class="well">
                    <div class="text-right">
                        <a class="btn btn-success">Leave a Review</a>
                    </div>
                    <hr>
                    <div class="row">
                        <div class="col-md-12">
                            <span class="glyphicon glyphicon-star"></span>
                            <span class="glyphicon glyphicon-star"></span>
                            <span class="glyphicon glyphicon-star"></span>
                            <span class="glyphicon glyphicon-star"></span>
                            <span class="glyphicon glyphicon-star-empty"></span>
                            Anonymous
                            <span class="pull-right">10 days ago</span>
                            <p>This product was great in terms of quality. I would definitely buy another!</p>
                        </div>
                    </div>
                    <hr>
                    <div class="row">
                        <div class="col-md-12">
                            <span class="glyphicon glyphicon-star"></span>
                            <span class="glyphicon glyphicon-star"></span>
                            <span class="glyphicon glyphicon-star"></span>
                            <span class="glyphicon glyphicon-star"></span>
                            <span class="glyphicon glyphicon-star-empty"></span>
                            Anonymous
                            <span class="pull-right">12 days ago</span>
                            <p>I've alredy ordered another one!</p>
                        </div>
                    </div>
                    <hr>
                    <div class="row">
                        <div class="col-md-12">
                            <span class="glyphicon glyphicon-star"></span>
                            <span class="glyphicon glyphicon-star"></span>
                            <span class="glyphicon glyphicon-star"></span>
                            <span class="glyphicon glyphicon-star"></span>
                            <span class="glyphicon glyphicon-star-empty"></span>
                            Anonymous
                            <span class="pull-right">15 days ago</span>
                            <p>I've seen some better than this, but not at this price. I definitely recommend this item.</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- jQuery -->
    <script src="js/jquery.js"></script>
    <!-- Bootstrap Core JavaScript -->
    <script src="js/bootstrap.min.js"></script>
</body>
</html>

teknosatis/teknosatis/Views/Home/Kategori.cshtml
@{
    ViewBag.Title = "Kategori";
}

<div class="panel-group" id="accordion">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h4 class="panel-title">
                <a href="Urunler/Telefonlar/1">@teknosatis.Resources.lang.Telefon</a>
            </h4>
        </div>
    </div>

    <div class="panel panel-default">
        <div class="panel-heading">
            <h4 class="panel-title">
                <a href="Urunler/Bilgisayarlar/1">@teknosatis.Resources.lang.Bilgisayar</a>
            </h4>
        </div>
    </div>

    <div class="panel panel-default">
        <div class="panel-heading">
            <h4 class="panel-title">
                <a href="Urunler/Kulaklıklar/1">@teknosatis.Resources.lang.Kulaklık</a>
            </h4>
        </div>
    </div>

    <div class="panel panel-default">
        <div class="panel-heading">
            <h4 class="panel-title">
                <a href="Urunler/Tabletler/1">@teknosatis.Resources.lang.Tablet</a>
            </h4>
        </div>
    </div>
</div>

teknosatis/teknosatis/Views/Home/Kategoriler.cshtml
@{
    ViewBag.Title = "Kategoriler";
}

<h2>Kategoriler</h2>

teknosatis/teknosatis/Views/Home/Listele.cshtml
@using PagedList
@using PagedList.Mvc
@model IPagedList<teknosatis.Models.Urun>
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title></title>
</head>
<body>
    <hr />
    <div class="row">
        @if (Model.Count() == 0)
        {
            <div class="row text-center"><h1>@teknosatis.Resources.lang.BuKategorideUrunYok</h1></div>
        }


        @foreach (var i in Model)
        {
            <div class="col-sm-4 col-xs-6 col-md-3 text-center">
                <div class="thumbnail">
                    <a href="@Url.Action("UrunDetay/"+@Html.DisplayFor(item => i.ID))"><img src=@Html.DisplayFor(item => i.ResimYol) class="img-responsive" alt="..."></a>
                    <div class="caption">
                        <h4>@Html.DisplayFor(item => i.Ad)</h4>
                        <p>@Html.DisplayFor(item => i.Detay)</p>
                        <p><span class="label label-success">@Html.DisplayFor(item => i.Fiyat) TL</span></p>
                    </div>
                </div>
            </div>
        }
    </div>
    <div class="pagedList row text-center">
        @Html.PagedListPager(Model, sayfa => Url.Action(ViewBag.Kategori + "/" + sayfa, "Urunler"), PagedListRenderOptions.PageNumbersOnly)
    </div>
</body>
</html>

teknosatis/teknosatis/Views/Home/UrunDetay.cshtml
@model teknosatis.Models.Urun

@{
    ViewBag.Title = @Html.DisplayFor(model => model.Ad) + " - " + @Html.DisplayFor(model => model.Detay);
}

<div class="row text-center">
    <div class="col-md-5">
        <img src="@Html.DisplayFor(model => model.ResimYol)" class="img-responsive" />
    </div>
    <div class="col-md-7">
        <p><h1 class="text-primary"><b>@Html.DisplayFor(model => Model.Ad)</b></h1></p>
        <p><h4>@Html.DisplayFor(model => Model.Detay)</h4></p>
        <p><h4 class="text-success">@Html.DisplayFor(model => Model.Fiyat) TL</h4></p>
        <p><a href="@Url.Action("SepetEkle/" + @Html.DisplayFor(model => model.ID),"Sepet")" class="btn btn-success">@teknosatis.Resources.lang.SepeteEkle</a></p>
    </div>
</div>

teknosatis/teknosatis/Views/Home/index_goster.cshtml
@model List<teknosatis.Models.Urun>

<hr />
<br />
<div class="row">
    @{
        foreach (var item in Model)
        {

            <div class="col-sm-4 col-lg-4 col-md-4">
                <div class="thumbnail">
                    <img src=@item.ResimYol alt="" href="Urunler/@item.Kategori/1" style="width:200px;height:150px">
                    <div class="caption">
                        <h4 class="pull-right">@item.Fiyat ₺</h4>
                        <h4>
                            <a href="Urunler/@item.Kategori/1">@item.Ad-@item.Detay</a>
                        </h4>
                     </div>
                </div>
            </div>
        }
    }
   
</div>